# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73d7c05dff1264f014941f0b7e03ae69c3bc8691af6f900f7df50061f52b5d4076df8c0769867a758795fd625b700d235042a5ff04bde1d72dcfc40e92176beb

test:
  secret_key_base: 7e377000b9bace0c92cb316e7b72357980bbb9ddbd7587dd9ffde707d7747b650b4d6dcb97ef3ba11068c0569806b8d8ace721a80b7b76d05a5b6ec758dda7fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
